### PR TITLE
Allow for non-status replies

### PR DESCRIPTION
**Pull request by cdn**

### CODE REVIEW

**Comment by mapkyca** [comment]
Could you provide a bit of information as to what this is meant to do?

**Comment by cdn** [comment]
> 
> 
> Could you provide a bit of information as to what this is meant to do?

Combined with changes to [photo](https://github.com/cdn/photo), and other plugins; these changes allow one to post a syndicated reply via Known including a photo (for example).
https://github.com/idno/known/issues/2350
https://github.com/idno/known/issues/2220

There is no Photo-reply type where [idno/status](https://github.com/idno/status) separates notes as status and reply.

**Comment by lindner** [comment]
Revisiting this PR is it still working?

**Comment by cdn** [comment]
> Revisiting this PR is it still working?

I need to test against HEAD of idno/Known

**Comment by definitelycn** [comment]
> > Revisiting this PR is it still working?
> 
> I need to test against HEAD of idno/Known

Having fixed part of my idno/photo fork, I think I can say “yes”

**Comment by cdn** [comment]
> Revisiting this PR is it still working?

Three replies to https://twitter.com/lindner/status/1290669445807927296

https://definitely.cn/2021/lindner-nonstatus-reply-to-test-postjavascript-parts
https://pushing.rocks/2021/01/20/lindner-drag-over-reply-to-a-site-still-works
https://red-pla.net/2021/lindner-once-more-from-a-fresh-checkout

**Review by lindner — APPROVED** [review]
LGTM, thanks for testing!

**Pull request merged**
